<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 *
 */
?>
<div id="my-tabs">
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Tab 1</span>
        </div>
    </div>
    <div data-role="content" class="tab-slider">
        <?= $block->getChildHtml('custom_phtml_block'); ?>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Tab 2</span>
        </div>
    </div>
    <div data-role="content">
        <button id="modal-btn">Open Modal</button>

        <div id="modal-content">
            <div class="modal-inner-content">
                <h2>Modal Title</h2>
                <p>Modal content.....</p>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#my-tabs": {
            "tabs": {},
            "customScript": {}
        },

        "#modal-btn": {
            "popup": {}
        }
    }
</script>
