<?php

/**
 * @var Magento\Framework\View\Element\Template $block
 * @var Magento\Framework\Escaper $escaper
 */

?>

<div id="customTabs">
    <div data-role="collapsible">
        <div data-role="trigger">
            <h2>Tab 1</h2>
        </div>
        <div data-role="content">
            <?php echo $block->getChildHtml('custom.tab1.container') ?>
        </div>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <h2>Tab 2</h2>
        </div>
        <div data-role="content">
            <?php echo $block->getChildHtml('custom.tab2.container')  ?>
        </div>
    </div>
</div>

<script>
    require(['tabs']);
</script>