<div class="tab1_container">
    <div class="custom-slick">
        <div>
            <img src="https://picsum.photos/600/600?random=1" alt="picsum" />
        </div>
        <div>
            <img src="https://picsum.photos/600/600?random=2" alt="picsum" />
        </div>
        <div>
            <img src="https://picsum.photos/600/600?random=3" alt="picsum" />
        </div>
        <div>
            <img src="https://picsum.photos/600/600?random=4" alt="picsum" />
        </div>
        <div>
            <img src="https://picsum.photos/600/600?random=5" alt="picsum" />
        </div>
        <div>
            <img src="https://picsum.photos/600/600?random=6" alt="picsum" />
        </div>
    </div>
</div>

<script>
    require(['tab1']);
</script>