<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 *
 */
?>
<button id="modal-btn">Open Modal</button>

<div id="modal-content">
    <div class="modal-inner-content">
        <h2>Modal Title</h2>
        <div data-role="content" class="tab-slider">
            <?= $block->getChildHtml('custom_phtml_block'); ?>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#modal-btn": {
            "popup": {}
        },

        "*": {
        "customScript": {}
        }

    }
</script>
